spring:
  application:
    name: foodsmap
  data:
    mongodb:
      uri: ${DB_URI:mongodb://foodsmap:foodsmap@127.0.0.1:27017/foodsmap?authSource=admin}
      ssl:
        enabled: ${DB_SSL:false}
        bundle: foodsmap
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:null}
            client-secret: ${GOOGLE_CLIENT_SECRET:null}
            scope:
              - email
              - profile
  ssl:
    bundle:
      pem:
        foodsmap:
          truststore:
            certificate: ${DB_CA_FILE:null}
  mail:
    host: ${SMTP_HOST:smtp.example.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:null}
    password: ${SMTP_PASSWORD:null}
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_TLS:true}
snowflake:
  worker-id: ${SNOWFLAKE_WORKER_ID:0}
  datacenter-id: ${SNOWFLAKE_DATACENTER_ID:0}
jwt:
  secret: ${JWT_SECRET}
cf-turnstile:
  secret: ${TURNSTILE_SECRET:1x0000000000000000000000000000000AA}
mail:
  from: ${MAIL_FROM:foodsmap@example.com}
  enabled: ${SEND_MAIL:false}